### ISSUE TITLE
Doesn't run on Apple Silicon

### ISSUE THREAD

**Issue by fastmot1on** [elanmart/cyberpunk-translator#4]
Hello, thanks for your amazing work. I'm struggling to get it to run on a M1 Mac environment - Running it on python 3.9 or 3.10 results in errors due to missing Mac modules - those seem to be all available on python 3.8 but then the code does not compile due to syntax errors:

```
(myCondaEnvironment) rafal@MacBook-M1 cbp_translate % python3.8 cbp_translate/cli.py --path-in ./assets/videos/keanu-reeves-interview.mp4 --path-out ./translated.mp4 --language PL

Traceback (most recent call last):
  File "cbp_translate/cli.py", line 4, in <module>
    from cbp_translate.pipeline import Config, run
  File "/Users/rafal/Crackground/cbp-translate/cbp_translate/pipeline.py", line 10, in <module>
    from cbp_translate.components.alignment import (
  File "/Users/rafal/Crackground/cbp-translate/cbp_translate/components/alignment.py", line 8, in <module>
    from cbp_translate.components.faces import FaceLocation, OnFrameRecognized
  File "/Users/rafal/Crackground/cbp-translate/cbp_translate/components/faces.py", line 13, in <module>
    from cbp_translate.components.loaders import frame_iterator, get_video_metadata
  File "/Users/rafal/Crackground/cbp-translate/cbp_translate/components/loaders.py", line 20, in <module>
    def get_video_metadata(path: str) -> tuple[int, int, tuple[int, int]]:
TypeError: 'type' object is not subscriptable

```

Any ideas are welcome :-)

**Comment by elanmart** [comment]
Hi @fastmot1on , apologies for the issue! I don't have an M1 macbook available at the moment, but I'll see what I can do over the weekend

**Comment by YusufCandraArif** [comment]
if you are using python < 3.9, you need to add, from __future__ import annotations
